### ISSUE TITLE
Doesn't work on OneUI 6 Beta

### ISSUE THREAD

**Issue by ris58h** [ris58h/galaxyfinder-widget#4]
A Reddit user complained that the widget doesn't work on OneUI6 Beta:

https://www.reddit.com/r/oneui/comments/zw9wo4/comment/jx7z0ys/

> Just tried it on One UI 6 beta and it doesn't work.

> It lets me download it, install it and place it. Once I place it, I can't click it, just seems Frozen. Got a message once saying it didn't work properly try clearing the cache, which I did. Still didn't work.

**Comment by ris58h** [comment]
Probably related to package visibility filtering.

https://developer.android.com/training/package-visibility

https://developer.android.com/guide/topics/manifest/queries-element

**Comment by ris58h** [comment]
I've added
```
<queries>
        <package android:name="com.samsung.android.app.galaxyfinder"/>
    </queries>
```
but it didn't help.

I don't have a device with OneUI beta so I can't reproduce the issue.

**Comment by xpusostomos** [comment]
Finder as an app appears to have disappeared in One UI 6, which is a shame because it was a useful entry point to the search function.

**Comment by ris58h** [comment]
@xpusostomos how did you know it?

**Comment by chups89** [comment]
Any solution, don't work on android 14 & oneui 6

**Comment by ris58h** [comment]
@Re-Tails made a fix. I'll release the new version soon.

Also @Re-Tails could you check that the app works without 
```
<queries>
    <package android:name="com.samsung.android.app.galaxyfinder"/>
</queries>
```
in `AndroidManifest.xml` for OneUI 6? It was my attempt to fix the issue but it seems like it's not necessary at all.

**Comment by Re-Tails** [comment]
> Also @Re-Tails could you check that the app works without 
> ```
> <queries>
>     <package android:name="com.samsung.android.app.galaxyfinder"/>
> </queries>
> ```
> in `AndroidManifest.xml` for OneUI 6? 

Yeah, it works with that removed as well 👍

**Comment by chups89** [comment]
@ris58h how soon will be release?)

**Comment by ris58h** [comment]
@chups89 it's available here https://github.com/ris58h/galaxyfinder-widget/releases/tag/v1.2

@Re-Tails could you also check that the released binary works for you?

**Comment by Re-Tails** [comment]
@ris58h Yep, the apk works perfectly.

**Comment by xpusostomos** [comment]
> @xpusostomos how did you know it?

Huh?

**Comment by xpusostomos** [comment]
> @chups89 it's available here https://github.com/ris58h/galaxyfinder-widget/releases/tag/v1.2
> 
> @Re-Tails could you also check that the released binary works for you?

Couldn't we have this APK be also a launchable app like Finder was before? Preferably with the Samsung identifiers so icon packs pick up the right icon.

**Comment by ris58h** [comment]
@xpusostomos you should create a separate issue.

**Comment by chups89** [comment]
@ris58h @Re-Tails 
Thank you very much.
